// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
)

type Product struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	Image       string    `db:"image" json:"image"`
	Price       float64   `db:"price" json:"price"`
	Description string    `db:"description" json:"description"`
	Quantity    int32     `db:"quantity" json:"quantity"`
	Stars       float64   `db:"stars" json:"stars"`
}
