// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addOrder = `-- name: AddOrder :one
INSERT INTO orders (product_id, quantity) VALUES ($1, $2) RETURNING id, product_id, quantity, order_date, status, created_at
`

type AddOrderParams struct {
	ProductID uuid.UUID `db:"product_id" json:"product_id"`
	Quantity  int32     `db:"quantity" json:"quantity"`
}

func (q *Queries) AddOrder(ctx context.Context, arg AddOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, addOrder, arg.ProductID, arg.Quantity)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Quantity,
		&i.OrderDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
