// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: service_order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_order_proto protoreflect.FileDescriptor

const file_service_order_proto_rawDesc = "" +
	"\n" +
	"\x13service_order.proto\x12\x02pb\x1a\x16rpc_create_order.proto2\x82\x01\n" +
	"\x0ebookstoreOrder\x12:\n" +
	"\vCreateOrder\x12\x16.pb.CreateOrderRequest\x1a\x11.pb.OrderResponse\"\x00\x124\n" +
	"\bGetOrder\x12\x13.pb.GetOrderRequest\x1a\x11.pb.OrderResponse\"\x00B9Z7github.com/siddheshRajendraNimbalkar/bookstore/order/pbb\x06proto3"

var file_service_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil), // 0: pb.CreateOrderRequest
	(*GetOrderRequest)(nil),    // 1: pb.GetOrderRequest
	(*OrderResponse)(nil),      // 2: pb.OrderResponse
}
var file_service_order_proto_depIdxs = []int32{
	0, // 0: pb.bookstoreOrder.CreateOrder:input_type -> pb.CreateOrderRequest
	1, // 1: pb.bookstoreOrder.GetOrder:input_type -> pb.GetOrderRequest
	2, // 2: pb.bookstoreOrder.CreateOrder:output_type -> pb.OrderResponse
	2, // 3: pb.bookstoreOrder.GetOrder:output_type -> pb.OrderResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_order_proto_init() }
func file_service_order_proto_init() {
	if File_service_order_proto != nil {
		return
	}
	file_rpc_create_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_order_proto_rawDesc), len(file_service_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_order_proto_goTypes,
		DependencyIndexes: file_service_order_proto_depIdxs,
	}.Build()
	File_service_order_proto = out.File
	file_service_order_proto_goTypes = nil
	file_service_order_proto_depIdxs = nil
}
