// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: service_product.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_product_proto protoreflect.FileDescriptor

const file_service_product_proto_rawDesc = "" +
	"\n" +
	"\x15service_product.proto\x12\x02pb\x1a\x18rpc_create_product.proto2V\n" +
	"\x0eProductService\x12D\n" +
	"\rCreateProduct\x12\x18.pb.CreateProductRequest\x1a\x19.pb.CreateProductResponseB;Z9github.com/siddheshRajendraNimbalkar/bookstore/product/pbb\x06proto3"

var file_service_product_proto_goTypes = []any{
	(*CreateProductRequest)(nil),  // 0: pb.CreateProductRequest
	(*CreateProductResponse)(nil), // 1: pb.CreateProductResponse
}
var file_service_product_proto_depIdxs = []int32{
	0, // 0: pb.ProductService.CreateProduct:input_type -> pb.CreateProductRequest
	1, // 1: pb.ProductService.CreateProduct:output_type -> pb.CreateProductResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_product_proto_init() }
func file_service_product_proto_init() {
	if File_service_product_proto != nil {
		return
	}
	file_rpc_create_product_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_product_proto_rawDesc), len(file_service_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_product_proto_goTypes,
		DependencyIndexes: file_service_product_proto_depIdxs,
	}.Build()
	File_service_product_proto = out.File
	file_service_product_proto_goTypes = nil
	file_service_product_proto_depIdxs = nil
}
